### ISSUE TITLE
Unable to close "About"

### ISSUE THREAD

**Issue by Luke-Nukem** [vertexclique/tokamak#12] opened 2016-04-05 23:32 UTC
As title. After clicking the "About" button, I am unable to find a way to close the dialogue box that pops up, without closing Atom.

**Comment by vertexclique** [comment] 2016-04-05 23:33
Duplicate of #7

**Comment by Luke-Nukem** [comment] 2016-04-05 23:34
Ah, same thing, different description.

**Closed** 2016-04-05 23:33 UTC
